### PR TITLE
Switched to the new object id generator

### PR DESCRIPTION
**Pull request by UltiNaruto**
PatcherState.fresh_instance_id_range is now deprecated
Custom blast shields now use memory relays instead of layers
Custom pickups now use memory relays instead of layers

### CODE REVIEW

**Review by toasterparty — COMMENTED** [review]
Please help with testing a corner case:
1) Competitive Cutscene Skip
2) Patch a door in tallon so that it's destination leads to temple security station

The room rando-style warp should work as intended

**Comment by UltiNaruto** [comment]
Any of the 2 doors of temple security station?

**Comment by toasterparty** [comment]
@UltiNaruto either is fine

**Comment by UltiNaruto** [comment]
Looks like it works well

Compared with 5.0-dev121

**Pull request merged**
