### PR TITLE
Added skip ridley patch

### PR DESCRIPTION
**Pull request by UltiNaruto**
# Skip Ridley patch

When enabled, it overrides the artifact count check to switch Artifact Temple to post Ridley fight instead of triggering the Ridley fight.

Preview : 

https://github.com/toasterparty/randomprime/assets/14176397/189ff69e-e1c7-4464-b7e6-3a29fbae0cd0

### CODE REVIEW

**Comment by toasterparty** [comment]
I would prefer if the totems were broken. Make sure to test with the new `competitiveskippable` cutscene mode,

**Comment by UltiNaruto** [comment]
> I would prefer if the totems were broken. Make sure to test with the new `competitiveskippable` cutscene mode,

I'll try to do that. Btw when you come back from impact crater it works fine which is a bit weird. I need to figure out why it won't work properly when you come from the cutscene.

**Comment by toasterparty** [comment]
because of the layer change

**Comment by UltiNaruto** [comment]
Updated the PR with a new commit

**Review by toasterparty — APPROVED** [review]

**Pull request merged**
